# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
before_install:
  - if [ ! -e $HOME/conda/bin/activate ]; then
    wget -nc https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh;
    bash Miniconda3-4.5.11-Linux-x86_64.sh -f -b -p $HOME/conda;
    fi
  - source $HOME/conda/bin/activate root
install:
- conda env update -f environment.yml
- pip install -r requirements_dev.txt
- pip install -U pluggy==0.6.0
script: pytest --cov
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/conda
before_cache:
  - rm $HOME/.cache/pip/log/debug.log $HOME/conda/bin/kripo $HOME/conda/lib/*/*/kripo.egg-link
